# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dummy.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x64ummy.proto\x12\x06mygrpc\"\x07\n\x05\x45mpty\"-\n\x12SampleDataResponse\x12\x17\n\x0fserialized_data\x18\x01 \x03(\t2N\n\x10SerializeService\x12:\n\rGetSampleData\x12\r.mygrpc.Empty\x1a\x1a.mygrpc.SampleDataResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dummy_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=23
  _globals['_EMPTY']._serialized_end=30
  _globals['_SAMPLEDATARESPONSE']._serialized_start=32
  _globals['_SAMPLEDATARESPONSE']._serialized_end=77
  _globals['_SERIALIZESERVICE']._serialized_start=79
  _globals['_SERIALIZESERVICE']._serialized_end=157
# @@protoc_insertion_point(module_scope)
