# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import anylog_node.tcpip.grpc.dummy_pb2 as dummy__pb2


class SerializeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSampleData = channel.unary_unary(
                '/mygrpc.SerializeService/GetSampleData',
                request_serializer=dummy__pb2.Empty.SerializeToString,
                response_deserializer=dummy__pb2.SampleDataResponse.FromString,
                )


class SerializeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSampleData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SerializeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSampleData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSampleData,
                    request_deserializer=dummy__pb2.Empty.FromString,
                    response_serializer=dummy__pb2.SampleDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mygrpc.SerializeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SerializeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSampleData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mygrpc.SerializeService/GetSampleData',
            dummy__pb2.Empty.SerializeToString,
            dummy__pb2.SampleDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
