# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vm.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08vm.proto\x12\nclihandler\"\x1d\n\nCliRequest\x12\x0f\n\x07KvmName\x18\x01 \x01(\t\"G\n\x0eResponseStatus\x12\x12\n\nScriptData\x18\x01 \x01(\t\x12\x11\n\tStatusMsg\x18\x02 \x01(\t\x12\x0e\n\x06Status\x18\x03 \x01(\x05\x32S\n\tHandleCli\x12\x46\n\x10HandleCliRequest\x12\x16.clihandler.CliRequest\x1a\x1a.clihandler.ResponseStatusB+Z)github.com/kubearmor-client/vm/clihandlerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vm_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z)github.com/kubearmor-client/vm/clihandler'
  _globals['_CLIREQUEST']._serialized_start=24
  _globals['_CLIREQUEST']._serialized_end=53
  _globals['_RESPONSESTATUS']._serialized_start=55
  _globals['_RESPONSESTATUS']._serialized_end=126
  _globals['_HANDLECLI']._serialized_start=128
  _globals['_HANDLECLI']._serialized_end=211
# @@protoc_insertion_point(module_scope)
