# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import vm_pb2 as vm__pb2


class HandleCliStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HandleCliRequest = channel.unary_unary(
                '/clihandler.HandleCli/HandleCliRequest',
                request_serializer=vm__pb2.CliRequest.SerializeToString,
                response_deserializer=vm__pb2.ResponseStatus.FromString,
                )


class HandleCliServicer(object):
    """Missing associated documentation comment in .proto file."""

    def HandleCliRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HandleCliServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HandleCliRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.HandleCliRequest,
                    request_deserializer=vm__pb2.CliRequest.FromString,
                    response_serializer=vm__pb2.ResponseStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'clihandler.HandleCli', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HandleCli(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HandleCliRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/clihandler.HandleCli/HandleCliRequest',
            vm__pb2.CliRequest.SerializeToString,
            vm__pb2.ResponseStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
