# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: infer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'infer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0binfer.proto\x12\x05infer\"v\n\x0ePredictRequest\x12\r\n\x05\x66rame\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\"\n\x06\x66ormat\x18\x04 \x01(\x0e\x32\x12.infer.PixelFormat\x12\x12\n\nrequest_id\x18\x05 \x01(\x03\"}\n\tDetection\x12\x0c\n\x04xmin\x18\x01 \x01(\x02\x12\x0c\n\x04ymin\x18\x02 \x01(\x02\x12\x0c\n\x04xmax\x18\x03 \x01(\x02\x12\x0c\n\x04ymax\x18\x04 \x01(\x02\x12\x12\n\nconfidence\x18\x05 \x01(\x02\x12\x10\n\x08\x63lass_id\x18\x06 \x01(\x05\x12\x12\n\nclass_name\x18\x07 \x01(\t\"K\n\x0fPredictResponse\x12$\n\ndetections\x18\x01 \x03(\x0b\x32\x10.infer.Detection\x12\x12\n\nrequest_id\x18\x02 \x01(\x03*K\n\x0bPixelFormat\x12\x1c\n\x18PIXEL_FORMAT_UNSPECIFIED\x10\x00\x12\t\n\x05\x42GR24\x10\x01\x12\t\n\x05RGB24\x10\x02\x12\x08\n\x04JPEG\x10\x03\x32\x90\x01\n\x10InferenceService\x12\x38\n\x07Predict\x12\x15.infer.PredictRequest\x1a\x16.infer.PredictResponse\x12\x42\n\rPredictStream\x12\x15.infer.PredictRequest\x1a\x16.infer.PredictResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'infer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PIXELFORMAT']._serialized_start=346
  _globals['_PIXELFORMAT']._serialized_end=421
  _globals['_PREDICTREQUEST']._serialized_start=22
  _globals['_PREDICTREQUEST']._serialized_end=140
  _globals['_DETECTION']._serialized_start=142
  _globals['_DETECTION']._serialized_end=267
  _globals['_PREDICTRESPONSE']._serialized_start=269
  _globals['_PREDICTRESPONSE']._serialized_end=344
  _globals['_INFERENCESERVICE']._serialized_start=424
  _globals['_INFERENCESERVICE']._serialized_end=568
# @@protoc_insertion_point(module_scope)
